export const FETCH_SHIPPING = 'FETCH_SHIPPING';
export const FETCH_SHIPPING_SUCCESS = 'FETCH_SHIPPING_SUCCESS';
export const FETCH_SHIPPING_FAIL = 'FETCH_SHIPPING_FAIL';
export const SET_SHIPPING = 'SET_SHIPPING';
