export const SET_ORDER_PRODUCT = 'SET_ORDER_PRODUCT';
export const SET_ORDER_VARIANT = 'SET_ORDER_VARIANT';
export const SET_ORDER_MESSAGE = 'SET_ORDER_MESSAGE';
export const SET_ORDER_DELIVERY = 'SET_ORDER_DELIVERY';
