export const FETCH_SHOP = 'FETCH_SHOP';
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAIL = 'FETCH_SHOP_FAIL';

export const SET_ORDER_PRODUCT = 'SET_ORDER_PRODUCT';
export const SET_ORDER_MESSAGE = 'SET_ORDER_MESSAGE';
export const SET_ORDER_DELIVERY = 'SET_ORDER_DELIVERY';
